import {
  User,
  PassengerProfile,
  DriverProfile,
  Company,
  Vehicle,
  Route,
  Trip,
  Transaction,
  Reward,
  ProposedRoute,
  Incident,
  AppNotification,
} from '../types';

export const mockCompany: Company = {
  id: 'comp-1',
  name: 'TransPerú Corporativo S.A.C.',
  ruc: '20601234567',
  address: 'Av. Las Begonias 441, San Isidro, Lima',
  contactEmail: 'operaciones@transperu-corp.com',
  contactPhone: '+51 (01) 619-4500',
  fleetSize: 18,
  activeEmployees: 340,
};

export const mockCurrentUserPassenger: User = {
  id: 'usr-p1',
  name: 'Camila Morales Vega',
  email: 'camila.morales@techcorp.pe',
  phone: '+51 987 654 321',
  avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  role: 'passenger',
  companyId: 'comp-1',
  companyName: 'TechCorp Perú (Cliente)',
  createdAt: '2025-01-15',
};

export const mockPassengerProfile: PassengerProfile = {
  userId: 'usr-p1',
  employeeCode: 'EMP-7482',
  department: 'Ingeniería de Software & Datos',
  assignedRouteIds: ['route-1', 'route-2'],
  homeStop: 'Estación Javier Prado',
  workStop: 'Campus Tecnológico Lurín',
  walletBalance: 48.50,
  corporateSubsidy: 150.00,
  points: 420,
  savedCarbonKg: 38.4,
};

export const mockCurrentUserDriver: User = {
  id: 'usr-d1',
  name: 'Carlos Mendoza Ríos',
  email: 'carlos.mendoza@transperu-corp.com',
  phone: '+51 976 543 210',
  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  role: 'driver',
  companyId: 'comp-1',
  companyName: 'TransPerú Corporativo',
  createdAt: '2024-03-10',
};

export const mockDriverProfile: DriverProfile = {
  userId: 'usr-d1',
  licenseNumber: 'Q-44589210',
  licenseCategory: 'A-IIIa Especial',
  vehicleId: 'veh-1',
  rating: 4.92,
  totalTrips: 1240,
  onTimePercentage: 97.4,
  status: 'on_trip',
  todayEarnings: 185.00,
  totalEarnings: 4620.00,
  experienceYears: 8,
};

export const mockRoutes: Route[] = [
  {
    id: 'route-1',
    name: 'Ruta 101 - Expreso San Isidro a Lurín',
    code: 'EXP-101',
    origin: 'Estación Javier Prado (San Isidro)',
    destination: 'Campus Industrial TechPark (Lurín)',
    distanceKm: 28.5,
    durationMinutes: 45,
    fare: 6.50,
    companyId: 'comp-1',
    companyName: 'TransPerú Corporativo',
    frequencyMinutes: 15,
    operatingHours: '06:00 - 22:30',
    activeBuses: 4,
    color: '#4A3184',
    coordinates: [
      [-12.0931, -77.0278],
      [-12.1154, -77.0195],
      [-12.1482, -76.9984],
      [-12.1856, -76.9723],
      [-12.2450, -76.9380],
      [-12.2820, -76.8790],
    ],
    stops: [
      { id: 'st-1', name: 'Estación Javier Prado (Inicio)', order: 1, lat: -12.0931, lng: -77.0278, etaMinutes: 0, address: 'Av. Javier Prado Este c/ Vía Expresa' },
      { id: 'st-2', name: 'Paradero Primavera / Encalada', order: 2, lat: -12.1154, lng: -77.0195, etaMinutes: 12, address: 'Av. Primavera 1280, Surco' },
      { id: 'st-3', name: 'Atocongo Intermodal', order: 3, lat: -12.1482, lng: -76.9984, etaMinutes: 22, address: 'Panamericana Sur km 11' },
      { id: 'st-4', name: 'Peaje Villa / Alipio Ponce', order: 4, lat: -12.1856, lng: -76.9723, etaMinutes: 30, address: 'Av. Pedro Miotta, SJM' },
      { id: 'st-5', name: 'Puente San Pedro (Lurín)', order: 5, lat: -12.2450, lng: -76.9380, etaMinutes: 38, address: 'Antigua Panamericana Sur km 29' },
      { id: 'st-6', name: 'Campus TechPark Puerta 1', order: 6, lat: -12.2820, lng: -76.8790, etaMinutes: 45, address: 'Av. Eucaliptos s/n, Lurín' },
    ],
  },
  {
    id: 'route-2',
    name: 'Ruta 204 - Corredor Norte Olivos a San Isidro',
    code: 'CORR-204',
    origin: 'MegaPlaza (Los Olivos)',
    destination: 'Centro Financiero San Isidro',
    distanceKm: 22.0,
    durationMinutes: 40,
    fare: 5.50,
    companyId: 'comp-1',
    companyName: 'TransPerú Corporativo',
    frequencyMinutes: 20,
    operatingHours: '06:30 - 21:00',
    activeBuses: 3,
    color: '#AB2E81',
    coordinates: [
      [-11.9922, -77.0620],
      [-12.0234, -77.0510],
      [-12.0580, -77.0370],
      [-12.0931, -77.0278],
    ],
    stops: [
      { id: 'st-21', name: 'MegaPlaza Panamericana Norte', order: 1, lat: -11.9922, lng: -77.0620, etaMinutes: 0, address: 'Av. Alfredo Mendiola 3698' },
      { id: 'st-22', name: 'Habich / UNI', order: 2, lat: -12.0234, lng: -77.0510, etaMinutes: 15, address: 'Av. Túpac Amaru 210' },
      { id: 'st-23', name: 'Centro Cívico / Av. Wilson', order: 3, lat: -12.0580, lng: -77.0370, etaMinutes: 28, address: 'Av. Garcilaso de la Vega 1337' },
      { id: 'st-24', name: 'Financiero San Isidro', order: 4, lat: -12.0931, lng: -77.0278, etaMinutes: 40, address: 'Av. Las Begonias 500' },
    ],
  },
  {
    id: 'route-3',
    name: 'Ruta 305 - Shuttle Aeropuerto Callao - Miraflores',
    code: 'AIR-305',
    origin: 'Aeropuerto Jorge Chávez (Callao)',
    destination: 'Parque Kennedy (Miraflores)',
    distanceKm: 18.0,
    durationMinutes: 35,
    fare: 7.00,
    companyId: 'comp-1',
    companyName: 'TransPerú Corporativo',
    frequencyMinutes: 30,
    operatingHours: '05:00 - 23:30',
    activeBuses: 2,
    color: '#F3A81A',
    coordinates: [
      [-12.0219, -77.1143],
      [-12.0621, -77.0872],
      [-12.1215, -77.0298],
    ],
    stops: [
      { id: 'st-31', name: 'Terminal Aéreo Callao', order: 1, lat: -12.0219, lng: -77.1143, etaMinutes: 0, address: 'Av. Faucett s/n' },
      { id: 'st-32', name: 'San Miguel / Plaza San Miguel', order: 2, lat: -12.0621, lng: -77.0872, etaMinutes: 18, address: 'Av. La Marina 2000' },
      { id: 'st-33', name: 'Parque Kennedy Miraflores', order: 3, lat: -12.1215, lng: -77.0298, etaMinutes: 35, address: 'Av. Larco 400' },
    ],
  },
];

export const mockVehicles: Vehicle[] = [
  {
    id: 'veh-1',
    plate: 'B8X-720',
    brand: 'Mercedes-Benz',
    model: 'Sprinter 516 CDI VIP',
    year: 2023,
    capacity: 20,
    occupiedSeats: 14,
    companyId: 'comp-1',
    driverId: 'usr-d1',
    driverName: 'Carlos Mendoza Ríos',
    status: 'active',
    fuelType: 'GNV',
    soatExpiry: '2026-11-20',
    technicalReviewExpiry: '2026-10-15',
    currentLat: -12.1482,
    currentLng: -76.9984,
    qrCode: 'TAPPI-VEH-B8X720-CORP',
  },
  {
    id: 'veh-2',
    plate: 'AYZ-915',
    brand: 'Volvo',
    model: 'B8R Urbano Colectivo',
    year: 2024,
    capacity: 32,
    occupiedSeats: 22,
    companyId: 'comp-1',
    driverId: 'usr-d2',
    driverName: 'Rosa Morales Quispe',
    status: 'active',
    fuelType: 'Eléctrico',
    soatExpiry: '2027-02-14',
    technicalReviewExpiry: '2026-12-05',
    currentLat: -12.0234,
    currentLng: -77.0510,
    qrCode: 'TAPPI-VEH-AYZ915-CORP',
  },
  {
    id: 'veh-3',
    plate: 'C3T-402',
    brand: 'Hyundai',
    model: 'County Bus Executive',
    year: 2022,
    capacity: 24,
    occupiedSeats: 0,
    companyId: 'comp-1',
    driverId: 'usr-d3',
    driverName: 'Jorge Huamán Silva',
    status: 'idle',
    fuelType: 'Gasolina',
    soatExpiry: '2026-09-30',
    technicalReviewExpiry: '2026-08-10',
    currentLat: -12.0931,
    currentLng: -77.0278,
    qrCode: 'TAPPI-VEH-C3T402-CORP',
  },
  {
    id: 'veh-4',
    plate: 'F7K-881',
    brand: 'Toyota',
    model: 'Coaster Hi-Roof',
    year: 2023,
    capacity: 26,
    occupiedSeats: 0,
    companyId: 'comp-1',
    driverId: 'usr-d4',
    driverName: 'Manuel Paredes Ruiz',
    status: 'maintenance',
    fuelType: 'Diésel',
    soatExpiry: '2026-12-01',
    technicalReviewExpiry: '2026-11-12',
    currentLat: -12.1856,
    currentLng: -76.9723,
    qrCode: 'TAPPI-VEH-F7K881-CORP',
  },
];

export const mockActiveTrip: Trip = {
  id: 'trip-current-1',
  routeId: 'route-1',
  routeName: 'Ruta 101 - Expreso San Isidro a Lurín',
  driverId: 'usr-d1',
  driverName: 'Carlos Mendoza Ríos',
  driverAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  driverRating: 4.92,
  driverPhone: '+51 976 543 210',
  vehicleId: 'veh-1',
  vehiclePlate: 'B8X-720',
  vehicleModel: 'Mercedes-Benz Sprinter 516 (Aire Acondicionado & WiFi)',
  status: 'in_progress',
  startTime: '07:15 AM',
  currentStopIndex: 2, // At Atocongo Intermodal
  capacity: 20,
  fare: 6.50,
  currentLat: -12.1482,
  currentLng: -76.9984,
  speedKmH: 48,
  etaNextStopMin: 8,
  passengers: [
    {
      passengerId: 'usr-p1',
      passengerName: 'Camila Morales Vega',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      employeeCode: 'EMP-7482',
      boardingStop: 'Estación Javier Prado',
      destinationStop: 'Campus TechPark Puerta 1',
      status: 'boarded',
      boardedAt: '07:18 AM',
      fare: 6.50,
      paidWith: 'subsidy',
    },
    {
      passengerId: 'usr-p2',
      passengerName: 'Andrés Valdivia Soto',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      employeeCode: 'EMP-3109',
      boardingStop: 'Estación Javier Prado',
      destinationStop: 'Campus TechPark Puerta 1',
      status: 'boarded',
      boardedAt: '07:19 AM',
      fare: 6.50,
      paidWith: 'wallet',
    },
    {
      passengerId: 'usr-p3',
      passengerName: 'Lucía Benavides Castro',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      employeeCode: 'EMP-5521',
      boardingStop: 'Paradero Primavera',
      destinationStop: 'Puente San Pedro',
      status: 'boarded',
      boardedAt: '07:27 AM',
      fare: 6.50,
      paidWith: 'subsidy',
    },
    {
      passengerId: 'usr-p4',
      passengerName: 'Mateo Quispe Flores',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      employeeCode: 'EMP-9012',
      boardingStop: 'Atocongo Intermodal',
      destinationStop: 'Campus TechPark Puerta 1',
      status: 'registered',
      fare: 6.50,
      paidWith: 'wallet',
    },
    {
      passengerId: 'usr-p5',
      passengerName: 'Sofía Herrera Paz',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      employeeCode: 'EMP-6643',
      boardingStop: 'Peaje Villa',
      destinationStop: 'Campus TechPark Puerta 1',
      status: 'registered',
      fare: 6.50,
      paidWith: 'subsidy',
    },
  ],
};

export const mockTripHistory: Trip[] = [
  {
    id: 'trip-past-101',
    routeId: 'route-1',
    routeName: 'Ruta 101 - Expreso San Isidro a Lurín',
    driverId: 'usr-d1',
    driverName: 'Carlos Mendoza Ríos',
    driverAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    driverRating: 5.0,
    driverPhone: '+51 976 543 210',
    vehicleId: 'veh-1',
    vehiclePlate: 'B8X-720',
    vehicleModel: 'Mercedes-Benz Sprinter',
    status: 'completed',
    startTime: 'Ayer, 06:00 PM',
    endTime: 'Ayer, 06:48 PM',
    currentStopIndex: 5,
    capacity: 20,
    fare: 6.50,
    currentLat: -12.2820,
    currentLng: -76.8790,
    speedKmH: 0,
    etaNextStopMin: 0,
    passengers: [],
  },
  {
    id: 'trip-past-102',
    routeId: 'route-1',
    routeName: 'Ruta 101 - Expreso San Isidro a Lurín',
    driverId: 'usr-d1',
    driverName: 'Carlos Mendoza Ríos',
    driverAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    driverRating: 4.9,
    driverPhone: '+51 976 543 210',
    vehicleId: 'veh-1',
    vehiclePlate: 'B8X-720',
    vehicleModel: 'Mercedes-Benz Sprinter',
    status: 'completed',
    startTime: 'Hace 2 días, 07:15 AM',
    endTime: 'Hace 2 días, 08:02 AM',
    currentStopIndex: 5,
    capacity: 20,
    fare: 6.50,
    currentLat: -12.2820,
    currentLng: -76.8790,
    speedKmH: 0,
    etaNextStopMin: 0,
    passengers: [],
  },
  {
    id: 'trip-past-103',
    routeId: 'route-2',
    routeName: 'Ruta 204 - Corredor Norte Olivos a San Isidro',
    driverId: 'usr-d2',
    driverName: 'Rosa Morales Quispe',
    driverAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    driverRating: 4.8,
    driverPhone: '+51 988 123 456',
    vehicleId: 'veh-2',
    vehiclePlate: 'AYZ-915',
    vehicleModel: 'Volvo B8R Eléctrico',
    status: 'completed',
    startTime: 'Hace 4 días, 08:00 AM',
    endTime: 'Hace 4 días, 08:44 AM',
    currentStopIndex: 3,
    capacity: 32,
    fare: 5.50,
    currentLat: -12.0931,
    currentLng: -77.0278,
    speedKmH: 0,
    etaNextStopMin: 0,
    passengers: [],
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: 'tx-1',
    passengerId: 'usr-p1',
    tripId: 'trip-current-1',
    amount: -6.50,
    type: 'payment',
    description: 'Pasaje en R-101 (Placa B8X-720)',
    date: 'Hoy, 07:18 AM',
    status: 'completed',
    receiptNumber: 'TP-2026-88419',
    paymentMethod: 'corporate_subsidy',
  },
  {
    id: 'tx-2',
    passengerId: 'usr-p1',
    amount: 50.00,
    type: 'recharge',
    description: 'Recarga digital vía Yape',
    date: 'Ayer, 03:25 PM',
    status: 'completed',
    receiptNumber: 'TP-REC-10942',
    paymentMethod: 'yape',
  },
  {
    id: 'tx-3',
    passengerId: 'usr-p1',
    tripId: 'trip-past-101',
    amount: -6.50,
    type: 'payment',
    description: 'Pasaje en R-101 Retorno',
    date: 'Ayer, 06:00 PM',
    status: 'completed',
    receiptNumber: 'TP-2026-88102',
    paymentMethod: 'tappi_wallet',
  },
  {
    id: 'tx-4',
    passengerId: 'usr-p1',
    amount: 150.00,
    type: 'subsidy',
    description: 'Abono Subsidio Movilidad Mensual TechCorp',
    date: '01 Sep 2026',
    status: 'completed',
    receiptNumber: 'SUB-CORP-SEP26',
    paymentMethod: 'corporate_subsidy',
  },
];

export const mockRewards: Reward[] = [
  {
    id: 'rew-1',
    title: 'Café Americano o Latte Gratis',
    description: 'Válido en Juan Valdez y Starbucks sede corporativa por 300 Puntos Tappi.',
    pointsCost: 300,
    discount: '100% OFF',
    partner: 'Coffee Hub Corporate',
    logo: '☕',
    category: 'cafeteria',
    claimed: false,
    code: 'TAPPI-COFFEE-2026',
  },
  {
    id: 'rew-2',
    title: 'Bono de S/ 15 en tu Billetera Tappi',
    description: 'Canjeable directamente para tus próximos viajes o recargas.',
    pointsCost: 400,
    discount: 'S/ 15 Saldo',
    partner: 'Tappi Mobility',
    logo: '💳',
    category: 'viajes',
    claimed: false,
    code: 'CASH-TAPPI-15',
  },
  {
    id: 'rew-3',
    title: '25% de Descuento en Smartwatch Deportivo',
    description: 'Equipos Garmin y Xiaomi en tienda oficial corporativa.',
    pointsCost: 550,
    discount: '25% OFF',
    partner: 'TechStore Perú',
    logo: '⌚',
    category: 'tecnologia',
    claimed: false,
    code: 'TECH-SPORT-25',
  },
  {
    id: 'rew-4',
    title: 'Pase Semanal Gimnasio SmartFit',
    description: 'Acceso a todas las sedes de Lima por movilidad activa.',
    pointsCost: 700,
    discount: 'Pase 7 Días',
    partner: 'SmartFit Corporativo',
    logo: '💪',
    category: 'bienestar',
    claimed: true,
    code: 'FIT-WEEK-CLAIMED',
  },
];

export const mockProposedRoutes: ProposedRoute[] = [
  {
    id: 'prop-1',
    passengerId: 'usr-p1',
    passengerName: 'Camila Morales Vega',
    companyName: 'TechCorp Perú',
    origin: 'Estación Central Metropolitano (Lima Centro)',
    destination: 'Parque Tecnológico Lurín (Planta 2)',
    preferredDepartureTime: '06:45 AM',
    estimatedPassengers: 28,
    votes: 42,
    status: 'in_study',
    createdAt: '2026-08-28',
  },
  {
    id: 'prop-2',
    passengerId: 'usr-p8',
    passengerName: 'Diego Alarcón Gil',
    companyName: 'Banca Seguros Corp',
    origin: 'Óvalo Higuereta (Surco)',
    destination: 'Centro Empresarial San Isidro',
    preferredDepartureTime: '07:30 AM',
    estimatedPassengers: 19,
    votes: 35,
    status: 'approved',
    createdAt: '2026-08-15',
  },
  {
    id: 'prop-3',
    passengerId: 'usr-p14',
    passengerName: 'Valeria Rivas Tello',
    companyName: 'Laboratorios Farmacéuticos',
    origin: 'Plaza San Miguel',
    destination: 'Planta Industrial Huachipa',
    preferredDepartureTime: '06:15 AM',
    estimatedPassengers: 22,
    votes: 18,
    status: 'review',
    createdAt: '2026-09-02',
  },
];

export const mockIncidents: Incident[] = [
  {
    id: 'inc-1',
    tripId: 'trip-current-1',
    reportedByRole: 'driver',
    reporterName: 'Carlos Mendoza Ríos',
    title: 'Congestión moderada en Puente Primavera',
    description: 'Obras de mantenimiento en carril derecho. Estimado retraso de 6 minutos.',
    category: 'retraso',
    severity: 'baja',
    status: 'en_proceso',
    timestamp: 'Hoy, 07:28 AM',
    vehiclePlate: 'B8X-720',
  },
  {
    id: 'inc-2',
    reportedByRole: 'company',
    reporterName: 'Central de Operaciones Tappi',
    title: 'Revisión técnica preventiva programada F7K-881',
    description: 'Unidad ingresó a taller oficial para cambio de pastillas de freno.',
    category: 'mecanico',
    severity: 'media',
    status: 'en_proceso',
    timestamp: 'Ayer, 04:00 PM',
    vehiclePlate: 'F7K-881',
  },
  {
    id: 'inc-3',
    reportedByRole: 'passenger',
    reporterName: 'Patricia Gómez',
    title: 'Objeto olvidado en asiento 12',
    description: 'Mochila color plomo con credencial corporativa dejada en turno tarde.',
    category: 'otro',
    severity: 'baja',
    status: 'resuelta',
    timestamp: '05 Sep 2026',
    vehiclePlate: 'AYZ-915',
    resolutionNote: 'Entregado en recepción de seguridad de TechCorp.',
  },
];

export const mockNotifications: AppNotification[] = [
  {
    id: 'notif-1',
    title: '¡Tu bus B8X-720 se aproxima!',
    message: 'El bus de la Ruta 101 llegará a tu paradero Estación Javier Prado en 4 minutos.',
    type: 'trip',
    timestamp: 'Hace 10 min',
    read: false,
  },
  {
    id: 'notif-2',
    title: 'Pago confirmado S/ 6.50',
    message: 'Se aplicó con éxito el subsidio corporativo de TechCorp para tu viaje.',
    type: 'payment',
    timestamp: 'Hace 35 min',
    read: false,
  },
  {
    id: 'notif-3',
    title: 'Nuevo beneficio disponible 🎉',
    message: 'Has alcanzado 420 Puntos Tappi. Puedes canjear tu café o bono de viaje.',
    type: 'promo',
    timestamp: 'Hoy, 06:00 AM',
    read: true,
  },
  {
    id: 'notif-4',
    title: 'Monitoreo de seguridad activo',
    message: 'Tu viaje cuenta con trazabilidad GPS en tiempo real y botón de SOS directo a central.',
    type: 'security',
    timestamp: 'Ayer',
    read: true,
  },
];
